sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t bskdockerhub/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bskdockerhub/docker-react npm run test

deploy:
  provider: elasticbeanstack
  region: "us-east-1"
  app: "docker-react"
  env: "dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-728626102994"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY